# RSS/Atom sources used for ingestion.
# default_region/default_type are fallbacks.

sources:
  - name: "AIB Insights"
    url: "https://insights.aib.world/feed"
    default_region: "Global"
    default_type: "other"

  - name: "EU Funding & Tenders Portal Updates"
    url: "https://ec.europa.eu/info/funding-tenders-opportunities/portal/screen/opportunities/topic-search/rss"
    default_region: "Europe"
    default_type: "funding"

  - name: "Horizon Magazine (EU R&I news)"
    url: "https://projects.research-and-innovation.ec.europa.eu/en/horizon-magazine/rss.xml"
    default_region: "Europe"
    default_type: "other"

  - name: "AOM Journals - AMJ eTOC"
    url: "https://journals.aom.org/action/showFeed?type=etoc&feed=rss&jc=amj"
    default_region: "Global"
    default_type: "journal"
