# Global academic funding, fellowships, and calls

sources:
  # ---------- EUROPE ----------
  - name: "EU Funding & Tenders – New Calls"
    url: "https://ec.europa.eu/info/funding-tenders/opportunities/data/referenceData/grantTenders-rss.xml"
    default_region: "Europe"
    default_type: "funding"

  - name: "ERC – European Research Council"
    url: "https://erc.europa.eu/news-events/rss.xml"
    default_region: "Europe"
    default_type: "funding"

  - name: "DFG – German Research Foundation"
    url: "https://www.dfg.de/en/service/rss/rss_calls"
    default_region: "Europe"
    default_type: "funding"

  - name: "Volkswagen Foundation"
    url: "https://www.volkswagenstiftung.de/en/news/rss"
    default_region: "Europe"
    default_type: "funding"

  # ---------- USA ----------
  - name: "NSF – Funding Opportunities"
    url: "https://www.nsf.gov/rss/rss_funding.xml"
    default_region: "North America"
    default_type: "funding"

  - name: "NIH – Grants & Funding"
    url: "https://grants.nih.gov/grants/rss/nih_grants.xml"
    default_region: "North America"
    default_type: "funding"
